steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Access the secret and write to a file
        echo "$$CLIENT_SECRET" > /workspace/client_secret.json
        # Build the Docker image
        docker build -t gcr.io/$PROJECT_ID/checkmychecks-cloud-backend .
    secretEnv: ['CLIENT_SECRET']

images:
  - 'gcr.io/$PROJECT_ID/checkmychecks-cloud-backend'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/client-secret-json/versions/latest
    env: 'CLIENT_SECRET'